version: '3.4'

services:
  sio.mailer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Store=Server=sio.sql.store;Initial Catalog=sio-store;User Id=sa;Password=1qaz-pl,
      - ConnectionStrings__Projection=Server=sio.mailer.sql.projections;Initial Catalog=sio-mailer-projections;User Id=sa;Password=1qaz-pl,
      - SMTP__Host=sio.mailhog
      - SMTP__Port=1025
    ports:
      - "5222:80"
      - "7222:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  sio.mailer.sql.projections:
    user: 'root'
    environment:
      SA_PASSWORD: "1qaz-pl,"
      ACCEPT_EULA: "Y"
    ports:
      - "1453:1433"
    volumes:
      - /var/opt/mssql/data
  sio.mailhog:
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui