version: '3.4'

services:
  sio.mailer:
    image: ${DOCKER_REGISTRY-}siomailer
    build:
      context: .
      dockerfile: src/SIO.Mailer/Dockerfile
    depends_on: 
      - sio.mailer.sql.projections
      - sio.mailhog
    external_links:
      - sio.sql.store
  sio.mailer.sql.projections:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
  sio.mailhog:
    image: mailhog/mailhog
networks:    
  default:
    external:
        name: sio.network
